function [fitresult, gof] = createFit(X, Y, Z)
%CREATEFIT1(X,Y,Z)
%  Create a fit.
%
%  Data for 'myfit' fit:
%      X Input: X
%      Y Input: Y
%      Z Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2024 15:00:45


%% Fit: 'myfit'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Z );

% Set up fittype and options.
ft = fittype( 'poly55' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'myfit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'myfit', 'Z vs. X, Y', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'X', 'Interpreter', 'none' );
ylabel( 'Y', 'Interpreter', 'none' );
zlabel( 'Z', 'Interpreter', 'none' );
grid on
view( 43.9, 55.7 );


